name: PsienceCI
on:
  push:
    branches:
      - edit

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: edit
      - name: Test
        uses: ./ci # Uses an action in the root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        args: [ 'tests' ]
